name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest # Chạy trên Windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Change Directory
        run: cd selenium_testing # Chuyển đến thư mục dự án

      - name: Build with Maven
        run: mvn clean install

      - name: Run Selenium Tests
        run: mvn test -DsuiteXmlFile=testng.xml # Chạy bài kiểm thử với TestNG
